# Generated by Django 4.1 on 2022-08-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerApp', '0002_paco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='camada',
        ),
    ]
