# Generated by Django 4.1 on 2022-08-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerApp', '0003_remove_familia_camada'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='edad',
            field=models.CharField(default='50', max_length=50),
        ),
        migrations.AddField(
            model_name='nico',
            name='edad',
            field=models.CharField(default='50', max_length=50),
        ),
    ]
